### ISSUE TITLE
Check for required packages while generating configs

### ISSUE THREAD

**Issue by berzerk54** [nixys/nxs-backup#1]
Can you add check for required packages? 
For example, when generating scp config, you will be unawared of missing packages, like 'sshpass' until the first run of backup utility. You will get the error like:
[2022-06-14 03:21:51]: Can't mount remote 'scp' storage: Required package 'sshpass' not installed!

After installing this package and running the utility again, you can get another error message because another package is missing, etc,etc..

And if you rarely check logs or mail, you may not even be aware of the problem until it's too late. Thanks in advance.

**Comment by randreev1321** [comment]
Hi.

Thanks for your interest in nxs-backup.

Your issue has been resolved in version 3.
