### ISSUE TITLE
MySQL connection parameters are stored in plain text in /tmp directory after each backup job

### ISSUE THREAD

**Issue by nskartem** [nixys/nxs-backup#12]
Hello,
As I found lately, nxs-backup is creating temporary files with DB connection data after each MySQL database backup job. Connection data is stored as a plain text without any obfuscation or protection.
That files are created in /tmp directory, and their permissions set to 644, so any user could possibly read their contents:
```
-rw-r--r-- 1 root      root       101 Jan  4 03:00 IUzAw-my_cnf_2024-01-04_03-00.ini
-rw-r--r-- 1 root      root        99 Jan  4 03:02 oBQ7E-my_cnf_2024-01-04_03-02.ini
-rw-r--r-- 1 root      root        99 Jan  4 03:04 sWbT4-my_cnf_2024-01-04_03-04.ini
-rw-r--r-- 1 root      root        99 Jan  4 03:06 6DTfj-my_cnf_2024-01-04_03-06.ini
-rw-r--r-- 1 root      root       101 Jan  5 03:00 AU0nG-my_cnf_2024-01-05_03-00.ini
-rw-r--r-- 1 root      root        99 Jan  5 03:02 9Ibhh-my_cnf_2024-01-05_03-02.ini
-rw-r--r-- 1 root      root        99 Jan  5 03:04 ip3Ks-my_cnf_2024-01-05_03-04.ini
-rw-r--r-- 1 root      root        99 Jan  5 03:06 kHCOs-my_cnf_2024-01-05_03-06.ini
```
That is a serious vulnerability, and I propose at least two things:
1. Remove temporary files after successful or unsuccessful completion of the job
2. Set permissions of the files to 600 so no one except file owner could read their contents

**Comment by randreev1321** [comment]
Hi.

Thanks for your interest in nxs-backup.

A fix for the issue has been included in the release [v3.2.0](https://github.com/nixys/nxs-backup/releases/tag/v3.2.0)

We look forward to receiving new requests.
