### ISSUE TITLE
Timeweb s3 storage problem

### ISSUE THREAD

**Issue by berzerk54** [nixys/nxs-backup#13]
Greetings
We encountered a problem when working with Timeweb s3 storage related to deleting old backups.

At the same time, there was no such problem when working with other S3 storages; we also checked Yandex and aws storages

```
ERROR [2024-01-12 03:00:06.233][projectname_s3-mysql](TimeWeb) Error detected during object deletion: '{  EOF}' 
ERROR [2024-01-12 03:18:43.226][projectname_s3-desc_files](TimeWeb) Error detected during object deletion: '{  EOF}' 
ERROR [2024-01-12 03:25:13.455][projectname_s3_inc_files](TimeWeb) Error detected during object deletion: '{  EOF}'
TimeWeb\n\nMessage: Error detected during object deletion: '{  <html>\n<head><title>502 Bad Gateway</title></head>\n<body>\n<center><h1>502 Bad Gateway</h1></center>\n<hr><center>nginx</center>\n</body>\n</html>}'","entities":[{"offset":20,"length":12,"type":"url"},{"offset":41,"length":18,"type":"url"}]}}
```

At the same time, there was no such problem when working with other S3 storages; we also checked Yandex and AWSstorages
The problem probably affects only timeweb storage.

**Comment by randreev1321** [comment]
Hi.

Thanks for your interest in nxs-backup.

Your issue has been resolved in version [3.1.0](https://github.com/nixys/nxs-backup/releases/tag/v3.1.0).
