### ISSUE TITLE
Additional alert

### ISSUE THREAD

**Issue by berzerk54** [nixys/nxs-backup#14]
Greetings,
We encountered an unpleasant problem with nxs-backup:
For some reason, the process of uploading backups to the remote s3-storage froze and was not completed, despite the fact that there were messages in the logs that the collection of backups had ended.

`# strace -p 496
strace: Process 496 attached
futex(0x7fff92393c70, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY`

The next day, the new collection of backups did not begin, because... the previous process was not completed and we did not receive any notifications or alerts that the nxs-backup job completed with an error or was not completed.

As a result, for several days we did not have backups and we were not aware of this.

To prevent the recurrence of such problems in the future, I suggest adding an alert if a new collection of backups is started, but the old one has not yet been completed.

**Comment by randreev1321** [comment]
Hi, @berzerk54.

Thanks for your interest in nxs-backup.

Totally agree, the logic has been updated in PR #33. The situation you encountered should not happen again. That said, you will receive a notification and a log entry in case another nxs-backup process has not yet completed.

These changes will be available in the next release.

**Comment by randreev1321** [comment]
Hi, @berzerk54.

The release [v3.4.0](https://github.com/nixys/nxs-backup/releases/tag/v3.4.0) is out.

We look forward to receiving new requests.
