### ISSUE TITLE
MongoDB collections from different dumps groups together in s3

### ISSUE THREAD

**Issue by mo-azizz** [nixys/nxs-backup#2]
In mongodb dumps if the database contains multiple collections from multiple dumps it is stored in this shape in s3:

* database 1:
  * daily:
    * collection1:
      * collection1-2022-05
      * collection1-2022-06
      * collection1-2022-07
    * collection2:
      * collection2-2022-05
      * collection2-2022-06
      * collection2-2022-07
      
But this creates a considerable complexity while restoring those dumps.

The more logical structure would be like this:

* database 1:
  * daily:
    * database1-2022-05:
      * collection1
      * collection2
    * database1-2022-06:
      * collection1
      * collection2
    * database1-2022-07:
      * collection1
      * collection2

This structure allows fetching and restoring the whole database in a single step without grouping the collections from different places.
Please provide a suitable structure for th ease of use.

**Comment by randreev1321** [comment]
Hi.

Thanks for your interest in nxs-backup.

Your issue has been resolved in version 3.
