### ISSUE TITLE
Error "Missing required key:''tmp_dir''" for type=inc_files

### ISSUE THREAD

**Issue by tellienne** [nixys/nxs-backup#22]
We generate 
`nxs-backup generate -S local -T inc_files -P /etc/nxs-backup/conf.d/example.conf`.

After that we use `nxs-backup start job-name` and get an error in the log file `ERROR [job-name] [2020-11-02 18:04:09]: Missing required key:''tmp_dir''!`

But config file for type=inc_files automatically generate without a key `tmp_dir`. 
Only when we add this key manually in config file it start to work. 

It work OK for type=desc_files.

**Comment by randreev1321** [comment]
Hello. 

Thank you for the feedback.

This issue was solved in [release 2.4.5](https://github.com/nixys/nxs-backup/releases/tag/v2.4.5)
