### ISSUE TITLE
Generate command hangs 

### ISSUE THREAD

**Issue by Elchinchel** [nixys/nxs-backup#50]
Hello! Running `nxs-backup generate -T desc_files -S name=sftp` hangs until keyboard interrupt.

nxs-backup version 3.8.0, also tried master branch (968678052978bd5eb31209925ca7b0d33d2f8575), same issue.

For me it looks like it hangs somewhere [here](https://github.com/nixys/nxs-backup/blob/968678052978bd5eb31209925ca7b0d33d2f8575/routines/cmd_handler/cmd_handler.go#L19).
As i can see, at the end of every other command (for example, selfUpdate.Run()) there is nil written to the done channel:
https://github.com/nixys/nxs-backup/blob/968678052978bd5eb31209925ca7b0d33d2f8575/modules/cmd_handler/self_update/self_update.go#L129
However, if generateConfig.Run() executes sucessfully, then it just returns:
https://github.com/nixys/nxs-backup/blob/968678052978bd5eb31209925ca7b0d33d2f8575/modules/cmd_handler/generate_config/generate_config.go#L371

If this was not intended, can you fix it, please?

**Comment by randreev1321** [comment]
Hi, @Elchinchel.

Thanks for your interest in nxs-backup.

This annoying bug will be fixed soon.

**Comment by randreev1321** [comment]
This has been fixed in version [3.8.1](https://github.com/nixys/nxs-backup/releases/tag/v3.8.1).

New ideas and suggestions are welcome.
