### ISSUE TITLE
Replacing localhost domain with ip

### ISSUE THREAD

**Issue by JoJoBizarrio** [nixys/nxs-backup#52]
Example:
sql has user like: user@localhost

mysql.conf has block:
connect:
  db_host: 'localhost'
  db_user:  'user' 
  db_password: 'password'
  
file /etc/hosts has:
127.0.0.1 localhost
::1      localhost

In this situation while command: 
`nxs-backup -t`
we will get error: **access denied for user@127.0.0.1 (or  user@::1)** 
_but must be user@localhost (its difference user for mysql)_

**Comment by randreev1321** [comment]
Hi, @JoJoBizarrio. 

Can you show the version of the DB server and the installed client? I am not able to reproduce your problem.

**Comment by randreev1321** [comment]
Hi, @JoJoBizarrio.

This is not an nxs-backup error, as it uses standard tools to connect to the DB server. This error indicates that the user is not allowed to connect over the network. 

If you display the list of users, you will see something like this:

```SQL
SELECT User, Host FROM mysql.user;

+------------------+-----------+
| User             | Host      |
+------------------+-----------+
| root             | localhost |
| root             | 127.0.0.1 |
| user             | localhost |
+------------------+-----------+
```

This means that the user can only connect using a socket, not the network.

Change the connection to socket, or add/change the user to allow network connections or any connections at all.

```yaml
sources:
  - name: mysql
    connect:
        socket: /var/run/mysqld/mysqld.sock
    	db_user: user
    	db_password: userP@5s
```
