### ISSUE TITLE
Проблема с storage ftp

### ISSUE THREAD

**Issue by Ragaga** [nixys/nxs-backup#6]
Утилита монтирует папку, но записать туда ничего не может. В качестве хранилища выступает selectel.
> INFO [2018-11-10 09:58:24]: Starting files block backup.
> INFO [SCANS-inc-files] [2018-11-10 09:58:24]: Starting backup for job 'SCANS-inc-files'.
> ERROR [SCANS-inc-files] [2018-11-10 09:58:25]: Couldn't open old decade meta info file '/mnt/curlftpfs/backup/scans/2018/month_11/daily/day_01/daily.inc': [Errno 2] No such file or directory: '/mnt/curlftpfs/backup/scans/2018/month_11/daily/day_01/daily.inc'!
> INFO [SCANS_ESTP-inc-files] [2018-11-10 09:58:25]: Finishing backup for job 'SCANS_ESTP-inc-files'.

Хотя файл на сервере создается, но размер 0
При этом если примонтировать сервер самому, а в качестве storage поставить local с указанием смонтированной папки, то файлы копируются нормально. 
UPDATE:
Ошибся, даже так не работает. 
конфиг выглядит так:
- job: SCANS-inc-files
    type: inc_files

    sources:
    - target: 
      - /path
      gzip: yes

    storages:
    - storage: ftp
      enable: yes

      backup_dir: /backup

      host: ''
      user: ''
      password: ''

curlftpfs 0.9.2 libcurl/7.47.0 fuse/2.9

**Comment by randreev1321** [comment]
Hello.

With the release of nxs-backup version 3, we changed the way of deliver backups to remote storage. The problem should not be an issue now.

If you are still experiencing problems with version 3, please report.
