### ISSUE TITLE
rsync + nsx-backup

### ISSUE THREAD

**Issue by flover97** [nixys/nxs-backup#7]
Рассматривали ли вы возможность использования rsync для скачивания фаловых бэкапов и их упаковки с удаленных машин? Было бы весьма полезно, если рассматривать ваше решение как центральный сервер для бэкапов.

**Comment by randreev1321** [comment]
Hi.

Thanks for your interest in nxs-backup.

We are not considering this possibility right now. You can use rsync in the external script for nxs-backup.
