### ISSUE TITLE
xtrabackup is untested on MariaDB

### ISSUE THREAD

**Issue by grooverdan** [nixys/nxs-backup#77]
xtrabackup includes a copy of large aspects of the innodb storage engine to perform its hot backups. For MySQL and Percona this is fine because it closely matches.

Because of ever diverging InnoDB code in MariaDB, MariaDB forked xtrabackup to (MariaDB-backup)[https://mariadb.com/kb/en/mariabackup/].

The execution and options of MariaDB-backup are still largely the same and compatible with the xtrabackup.

If you could adjust the command execution for MariaDB this would save our mutual users from database corruption on restoration.

Making front page readme not include MariaDB under the xtrabackup would be much appreciated.

**Comment by randreev1321** [comment]
Hi @grooverdan, thank you for reporting this issue. 

We will fix the documentation as soon as possible. We will try to work with mariabackup in the next releases.

**Comment by randreev1321** [comment]
Hi @grooverdan.

We have added support for mariadb-backup for MariaDB users and introduced a new backup type for this purpose. The changes are available in the [3.12.0](https://github.com/nixys/nxs-backup/releases/tag/v3.12.0) release.

Also updated the description on the [documentation page](https://nxs-backup.io/documentation/stable/3-3-2-xtrabackup-mysql-physical-backups/).

New ideas and suggestions are welcome.

**Comment by grooverdan** [comment]
Thank you very much!
