### ISSUE TITLE
The psql_ssl_mode parameter does not work: when specifying a connection to the Postgresql service via a socket

### ISSUE THREAD

**Issue by Patebash** [nixys/nxs-backup#8]
Hello.

I am instructing the nxs-backup service to connect to the Postgres database via a socket with the following parameters:

```
connect: 
socket: /var/run/postgresql/.s.PGSQL.5432 
psql_ssl_mode: "disable" 
db_user: postgres
```
I get an error message when checking the configuration:

```
# nxs-backup
Failed initialization of jobs with the following errors:
1 error occurred:
* Failed to initialize the `server-postgresql` job. User: `postgres`, db: `, SQL connect error: pq: SSL is not enabled on the server
```

It seems that the psql_ssl_mode: "disable" option does not work when connected via socket

**Comment by randreev1321** [comment]
Hi @Patebash.

Thanks for your interest in nxs-backup.

Could you please specify which version of PostgreSQL you were using when you encountered this issue?

**Comment by randreev1321** [comment]
As part of PR #29, edits were prepared to fix a problem with connecting to PSQL via socket. A release [v3.2.1](https://github.com/nixys/nxs-backup/releases/tag/v3.2.1) containing these fixes has been released.

Please check the updated version. If you have any new questions, we will be happy to help.
