### ISSUE TITLE
Wrong interpretation cmd

### ISSUE THREAD

**Issue by JoJoBizarrio** [nixys/nxs-backup#88]
For example, when conf file has two or more space between key, like:

`db_extra_keys: "--key1 --key2          --key3 " `

we will have next error:

```
DEBUG [2024-09-30 05:32:45.246][backup-mysql] Dump cmd: /usr/bin/mysqldump --key1 --key2          --key3 databaseName
INFO [2024-09-30 05:32:45.247][backup-mysql] Starting a `databaseName` dump
ERROR [2024-09-30 05:32:45.312][backup-mysql] Unable to dump `databaseName`. Error: mysqldump: Got error: 1046: "No database selected" when selecting the database
```

**Comment by randreev1321** [comment]
Hi @JoJoBizarrio, thanks for your activity, the problem has been fixed in [v3.12.1](https://github.com/nixys/nxs-backup/releases/tag/v3.12.1).
