### ISSUE TITLE
one broken job breaks all other jobs

### ISSUE THREAD

**Issue by berzerk54** [nixys/nxs-backup#9]
Hello
We encountered an unpleasant situation: backups were not collected for a couple of days due to errors in the jobs config.
There are several jobs that worked properly, but among them there was one unconfigured job. As a result, all backups were not collected for several days, alerts also did not arrive by email, apparently because checking the correctness of backups did not work properly.

```
# nxs-backup --version
nxs-backup v3.0.2
```

after the “broken” config was removed from conf.d, everything works normally, but I would like to either receive alerts about a problem with the configs, or have live jobs processed separately, regardless of the presence of problematic jobs

**Comment by randreev1321** [comment]
Hi, @berzerk54.

We have changed the behavior of nxs-backup.

Now jobs that were initialized correctly will be executed when running the backup, even if errors were detected. If notification channels are configured, you will be notified of errors detected during initialization.

The situation you described is excluded if the configuration file can be read. This update will be available in version 3.5.0 which we will release soon.

In any case, when making any changes to the configuration, it is recommended to perform a validation of the config to avoid similar situations in the future.

Thank you for your interest in nxs-backup. We will be glad to receive new suggestions.
