### ISSUE TITLE
Connecting to MySQL with SSL

### ISSUE THREAD

**Issue by sofanixys** [nixys/nxs-backup#92]
Add additional config options in order to connect to MySQL server via SSL.

**Comment by randreev1321** [comment]
Hi @sofanixys. 

We have added parameters for connecting to MySQL using client certificates in [v3.12.1](https://github.com/nixys/nxs-backup/releases/tag/v3.12.1). 

This functionality now works with MySQL 8.0 and higher. We encountered a problem, when connecting to MySQL 5.7 there is a `tls handshake` error. To solve this problem, [issue](https://github.com/go-sql-driver/mysql/issues/1635) has been opened.
